first commit of the portfolio
malembi/Portfolio pull request #1
Opened 2023-01-13 08:09 UTC by malembi

This first commit includes the beginning of the project whereby all files needed for the project are added.

2023-01-13 09:09 UTC, brainconnect93 requested changes
# STATUS: Changes Required :recycle:

### Hi @malembi, 👋 

Good job so far, You really made a great effort working on your project, it looks really awesome! but there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 09:09 UTC, brainconnect93 commented on style.css
> +}
- [ ] As given in the project requirement, it is necessary for you to follow the Figma template as much as possible. Currently, I notice some differences in your project compared with the Figma design. Kindly check below some highlights of where you need to work on: 👇 

   - Kindly remove the underline in your `Logo` to look exactly like what we have in the Figma template. 
   > N.B: It will be fine if you can personalize the `Logo` name
   - Currently, the link to your `hamburger` icon is broken and it's not showing from my end. Kindly fix it. Note that it is best practice to always add an `alternative text` to your image in order to give a proper user experience and to give the visitor an idea of what the image is all about even if the link is broken.
   - As shown in the Figma design, kindly import the `font family` name from google as currently the `font family` you have in your project looks different from what we have in the Figma design
   - As shown in the Figma design, your project is missing the background color, I notice you have it in your project but it seems you are targeting the image directory wrongly.

Your design 👇 

![mal](https://user-images.githubusercontent.com/78634841/212281248-a547e679-a614-45c9-af9b-3e9a7ce3c7d2.png)

Figma template 👇 

<img src="https://user-images.githubusercontent.com/78634841/211955944-48618eb2-638d-438c-9105-aa5cdefb45ad.png">

2023-01-13 11:27 UTC, malembi commented on index.html
> +   </div>
@brainconnect93 I made the required changes.

2023-01-13 12:22 UTC, malembi commented
Made the changes required which were:-
>removed the line under my logo.
> Added the alternative text in my image icon  to give it a proper user experience.
>Imported the font family from google.
>Changed my background color to the specified one.

2023-01-13 12:43 UTC, roshan-bajgain requested changes
Hi @malembi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 12:43 UTC, roshan-bajgain commented on index.html
> +  <img src="Assets/Union.png" class="nav-bar" alt="icon" >
- [ ] As requested by the previous reviewer your hamburger icon is broken and it's not showing. Please fix it
### Your design
![your](https://user-images.githubusercontent.com/81727988/212320850-df040794-f9fa-49bd-9f51-a3edd69ff828.jpg)


### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/212321046-c3b77add-c327-45c1-9364-582be2338c63.jpg)

2023-01-13 12:43 UTC, roshan-bajgain commented on index.html
> +  </li>
- [ ] As requested by the previous reviewer use the background image. See the image below for reference
- [ ] First reviewer did not give a review as it was good before but is not the same as the Figma design So please manage the social icons to match the Figma design.
- [ ] Also fix the left spacing of the content as it is hidden from the left side. Please do so.
### Your design
![your](https://user-images.githubusercontent.com/81727988/212322337-428f1d0b-6ed7-4679-88c3-646cd3eddcef.jpg)



### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/212322252-01d4b060-c55f-483d-826d-99f47c3f015d.jpg)

2023-01-13 14:19 UTC, malembi commented on index.html
> +  <img src="Assets/Union.png" class="nav-bar" alt="icon" >
maybe you should help with an idea of how to do it.

2023-01-13 19:16 UTC, Tadesse-Alemayehu requested changes
### Hi @malembi 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![199733072-bdacca19-8df9-43a7-be93-3aff2f1c15c8](https://user-images.githubusercontent.com/69077061/204107907-c2532abb-b23d-4fda-88f0-1ec9c7b71971.gif)

 ## Highlights
 - [ ] Good job making most of the changes requested by the previous reviewer. 🙏
 - [ ] Good job overall following the template design 💯
 - [ ]  Correct GitHub Flow 👍🏾
 - [ ]  All linters passed 🥇

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 19:16 UTC, Tadesse-Alemayehu commented on style.css
> +  background-position: top center;
- [ ] Dear @malembi, I see the previous reviewer ask for the visibility of the decoration image, the problem here is that you used an invalid `URL` for locating an image and as a result of this the decoration is not visible. Please make sure your background is visible before the next review.

2023-01-13 19:16 UTC, Tadesse-Alemayehu commented on index.html
> +</nav>
- [ ] Dear @malembi, I see the previous reviewer ask for the visibility of the hamburger icon, the problem here is that you used an invalid `URL` (`Assets./Union.png`) for locating an image and as a result of this the hamburger icon is not visible. Please make sure your hamburger is visible before the next review.

2023-01-13 19:16 UTC, Tadesse-Alemayehu commented on index.html
> +        <p class="link">LET'S CONNECT</p>
### Dear @malembi, You are doing great, there are some minor details not addressed yet, Please look through the suggestion down. 
- [Optional] Your titles are too big compared with the Figma design, Please try to use a font size that is closely related to the Figma design.
- [Optional] Your `My Logo` text is underlined. As you can check from the Figma design this part is not underlined and a bit bolder than your design. Please address this for a better layout. 
- [Optional] Good job removing the list style from your social media icons, but till you social media icons are small and with a different color than a Figma design, Pleas fix this to make your design as close as the Figma design. 

![Screenshot 2023-01-13 220040](https://user-images.githubusercontent.com/69077061/212400195-3f276491-b9ae-4702-b041-fcaa47c043a8.png)

2023-01-14 16:43 UTC, malembi commented
Started the project fresh because of different advice from different reviewers.
Most changes made are on Html and CSS.

2023-01-14 18:03 UTC, AlphaNtihinduka requested changes
## Hi @Ibizugbe    🙋‍♂️
Good job working on implementing the changes required by the previous reviewers. You have done the design to the expectation and incredibly well. 👏  

TO HIGHLIGHT:
- Your project is professional :heavy_check_mark: 
- Professional README file :100: 
- Your PR is not yet professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- No linter errors :heavy_check_mark: 

# STATUS: Required Changes :recycle: 

![close](https://user-images.githubusercontent.com/99394374/210771148-619a4265-33b2-4e68-8901-6bb52693d6de.gif)

## Required changes :recycle: 
- I have noticed that most of the changes are about the `design` and semantic use of `ul` and `li`. Kindly check the inline comments below and apply changes as required.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or slack channel if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK :crossed_fingers: :four_leaf_clover:

2023-01-14 19:44 UTC, malembi commented
I have made the necessary changes. however, I have noticed some of the fonts Figma  have to be customized to fit my website therefore I made the necessary adjustments. In this regard, I have also noticed my coding partner has some customizations and the reviews are successful, I find this contradicting and at the same time frustrating if we have contradicting reviews.

2023-01-14 20:20 UTC, AlphaNtihinduka commented
Dear Malembi,
The sizes stated in figma may be customized. However when implementing this, try to compare the 2 designs so that it doesn't look much different from the one in figma. Hope this one helps. Kindly lete know if there is something else not clear 🙏

2023-01-14 20:58 UTC, MeqdamAlqudah requested changes
Hi @malembi , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![image](https://user-images.githubusercontent.com/74744787/212496568-31e79f1f-5602-43b5-ba5a-acb5169326bd.png)

 ## Highlights
:+1: no linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 20:58 UTC, MeqdamAlqudah commented on index.html
> +<section class="icons">
- [Optional] Please LET's Connect suppose to be a link or a button

2023-01-14 20:58 UTC, MeqdamAlqudah commented on index.html
> +      </h1>
- [Optional] Please the margin here is destroying the page  😅 please remove it 
![image](https://user-images.githubusercontent.com/74744787/212494245-b7f26005-293e-4ac3-9c2c-6d2c653624e2.png)

2023-01-14 20:58 UTC, MeqdamAlqudah commented on index.html
> +  <img src="Union.png" class="nav-bar">
- [  ] Please as the last reviewer said, the logo suppose to be a link to the home page in the `a` tag, also the `nav` tag suppose to contain navigational links the logo should be not included, if you open websites as Facebook or youtube the logo send you to the home page so it is the same thing here.

2023-01-14 20:58 UTC, MeqdamAlqudah commented on style.css
> +  background-image: url('header-shapesmobile.png');
- [ ] Good Job by changing the background to be in CSS as the last reviewer said but you should also make it not repeatable so it matches the design.
![image](https://user-images.githubusercontent.com/74744787/212496322-ad921593-5132-403b-9fa5-283d2e3d7940.png)

2023-01-14 20:58 UTC, MeqdamAlqudah commented on style.css
> +  display: flex;
- [ ] Please make sure that you have the same margin here as in the design 

your code 
![image](https://user-images.githubusercontent.com/74744787/212496398-30297980-d905-487a-822e-d0e92b1ad4c0.png)

Figma 
![image](https://user-images.githubusercontent.com/74744787/212496406-2bfab680-9288-4f9f-971d-4143dbdd2351.png)

I know these comments about the font size and the margin are hard but belive me giving the exact 100% design to the client is a very valuable skill.

2023-01-14 20:58 UTC, MeqdamAlqudah commented on style.css
> +  display: flex;
- [ Optional ] Please make sure to remove this unnecessary margin here it makes the page looks weird and doesn't match the design.
![image](https://user-images.githubusercontent.com/74744787/212496519-1f0eb378-a6ed-4d7d-beab-5100ec96d8c9.png)

2023-01-15 19:18 UTC, malembi commented on style.css
> +  background-image: url('header-shapesmobile.png');
I made the necessary changes needed.

2023-01-15 19:31 UTC, malembi commented on style.css
> +  display: flex;
done

2023-01-15 19:43 UTC, malembi commented on style.css
> +  display: flex;
done

2023-01-15 20:39 UTC, malembi commented on .github/workflows/linters.yml
> +      - uses: actions/setup-node@v1
done

2023-01-15 20:40 UTC, malembi commented on index.html
> +<section class="icons">
done

2023-01-15 20:40 UTC, malembi commented on index.html
> +      </h1>
done

2023-01-15 20:40 UTC, malembi commented on index.html
> +  <img src="Union.png" class="nav-bar">
done

2023-01-15 20:41 UTC, malembi commented on style.css
> +  background-image: url('header-shapesmobile.png');
done

2023-01-15 20:41 UTC, malembi commented on style.css
> +  display: flex;
done

2023-01-15 20:41 UTC, malembi commented on style.css
> +  display: flex;
done

2023-01-16 08:23 UTC, Shedrack-Sunday requested changes
Hi @malembi  ,


CHANGES REQUIRED ♻️
Great work on making considerable progress in implementing also all the requirements of the project so far 👏
However, there are still a few which aren't been addressed yet.

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)


Highlight
✅All linters are checked.
✅ Proper setup
✅ Descriptive commit messages


Required Changes ♻️

- [ ] The slight change needed has to do with your `nav` Section, of which I've made a detailed review. Kindly check the comment section for the suggestion I requested in line with the [Project Requiremnst](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/1_setup.md)

Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.


Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-16 08:23 UTC, Shedrack-Sunday commented on index.html
> +      </header>
- [ ] Based on the picture I attached below, you can see that the hamburger button is not aligned to the right properly. please follow the requirement to align the with flexbox, to make it beautiful. 👍 
## Your design:
![image](https://user-images.githubusercontent.com/50990925/212628879-db3df8b2-8fc2-4dd6-b632-915ff1334798.png)

## Figma
![image](https://user-images.githubusercontent.com/50990925/212628954-d7e605df-79ff-4954-9358-8ea489e0aed7.png)

2023-01-16 08:23 UTC, Shedrack-Sunday commented on README.md
>  > Give credit to everyone who inspired your codebase.
- [ ] Kindly do well to always remove this section of the README . It a suggestion for you, but should not be added to your codebase: Good job 👍

2023-01-16 09:22 UTC, malembi commented on README.md
done

2023-01-16 09:22 UTC, malembi commented on .gitignore
> +test.md
removed test.md

2023-01-16 09:42 UTC, malembi commented on README.md
> -
done

2023-01-16 09:44 UTC, malembi commented on README.md
> -
done

2023-01-16 09:47 UTC, malembi commented on index.html
> +      </header>
done

2023-01-16 10:44 UTC, OyePriscilla requested changes
Hi @malembi 😃, 

You've really done a great work, I must confess!

There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425615-8927e377-c543-407b-8da4-5c09fecc261b.gif)

## Highlights
Github flow observed✔️
Linters Set up correctly ✔️ 

## Required Changes ♻️


## Optional suggestions

- [optional] Your PR title and summary are not descriptive enough. Writing descriptive titles allows us to see what happened for each set of merged changes; and a summary of what changes have been applied for this pull request should be a short description of the changes. ℹ️ 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 10:44 UTC, OyePriscilla commented on README.md
>  - **[key_feature_3]**
- [ ] Please kindly add the key features as suggested earlier. 👍 Key features will give an overview of what your app is all about. Perhaps, build a responsive portfolio, Make app dynamic using JS, ... ℹ️

2023-01-16 10:44 UTC, OyePriscilla commented on README.md
> +- [ ] **[new_feature_3]**
- [ ] Please ensure to add at least two or three features that you wish to implement later. 👍 The previous reviewer pointed this out as well. 👍

2023-01-16 10:44 UTC, OyePriscilla commented on test.md
> +this file should be ignored by git
- [ ] Kindly delete this file totally from your app folder since it is not needful, doing this will make your codebase cleaner. Thanks. 💁‍♂️

2023-01-16 11:08 UTC, malembi commented on test.md
> +this file should be ignored by git
deleted

2023-01-16 11:11 UTC, malembi commented on README.md
>  - **[key_feature_3]**
done

2023-01-16 11:24 UTC, ha-manel approved these changes
# STATUS: APPROVED ✅

## Hi @malembi 👋

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: 
**Congratulations! 🎉**

<img src="https://media3.giphy.com/media/l4JySAWfMaY7w88sU/giphy.gif"/>

## Highlights:
* All tests passed ✔️ 

## Optional suggestions:

- [x] Please consider using best practices when you write commit messages, they should be capitalized sentences in the imperative form, example: "Add linters" instead of "added linters" or "linters are added" ... etc 👍 
- [ ] From now on, please write descriptive pull request titles and descriptions, for example in this milestone, the title could be "Portfolio: headline section" for the description please enlist all the changes that were made by you in this branch. Please not that pull requests with unprofessional title and description normally get invalid.
- [x] Kindly consider filling all the README file's sections with information about your project for professional documentation. Leaving the placeholder text in the README looks unprofessional 😓 


------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 11:30 UTC, merged